# Site settings
title: Zayd Bille
email: zayd.tri@gmail.com
description: "I'm Zayd. A Software Developer from Ottawa Ontario. Join me in my fearless quest that I call life."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF   #EB5B02 #18bc9c
  secondary: FD6E8A   #692800 #2c3e50
  secondary-dark: A2122F   #3E1800 #233140

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/silverherok
  - title: linkedin
    url: http://linkedin.com/in/zayd-bille
  - title: stack-overflow
    url: https://stackoverflow.com/users/2847130/waves
  - title: google-plus 
    url: https://plus.google.com/u/0/110530537560074828207
  - title: github
    url: https://github.com/Zayd-Waves

# Postal address (add as many lines as necessary)
address:
  - line: Ottawa, Ontario
  - line:

# Build settings
markdown: kramdown
permalink: pretty
