# Site settings
title: Zayd Bille
email: zayd.tri@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EB5B02 #18bc9c #80B3FF
  secondary: 692800 #2c3e50 #FD6E8A
  secondary-dark: 3E1800 #233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/silverherok
  - title: linkedin
    url: http://linkedin.com/in/zayd-bille
  - title: stack-overflow
    url: https://stackoverflow.com/users/2847130/waves
  - title: google-plus 
    url: https://plus.google.com/u/0/110530537560074828207
  - title: github
    url: https://github.com/Zayd-Waves

# Postal address (add as many lines as necessary)
address:
  - line: Ottawa, Ontario
  - line:

# Build settings
markdown: kramdown
permalink: pretty
